import type { Config } from 'jest';

const config: Config = {
  rootDir: '.',
  testEnvironment: 'node',
  preset: 'ts-jest',
  testRegex: '.*\\.spec\\.ts$',
  moduleFileExtensions: ['ts', 'tsx', 'js', 'json'],
  transform: {
    '^.+\\.(t|j)s$': [
      'ts-jest',
      {
        tsconfig: {
          esModuleInterop: true,
          experimentalDecorators: true,
          emitDecoratorMetadata: true,
          target: 'ES2021',
          module: 'commonjs',
          allowSyntheticDefaultImports: true,
          strictNullChecks: false,
          noImplicitAny: false,
        },
        isolatedModules: true,
        diagnostics: false,
      },
    ],
  },
  moduleNameMapper: {
    '^src/(.*)$': '<rootDir>/src/$1',
  },
  roots: ['<rootDir>/src', '<rootDir>/test'],
  setupFiles: ['<rootDir>/test/jest.setup.ts'],
  clearMocks: true,
  resetMocks: false,
  restoreMocks: true,

  collectCoverage: false,
  coverageDirectory: 'coverage',
  coverageProvider: 'babel',
  coverageReporters: ['text', 'text-summary', 'html', 'lcov', 'json-summary'],
  collectCoverageFrom: [
    'src/**/*.ts',
    '!src/main.ts',
    '!src/**/*.module.ts',
    '!src/**/*.dto.ts',
    '!src/**/*.entity.ts',
    '!src/**/*.schema.ts',
    '!src/**/*.model.ts',
    '!src/**/*.interface.ts',
    '!src/**/*.provider.ts',
    '!src/**/dtos/**',
    '!src/**/migrations/**',
    '!src/**/seeders/**',
    '!src/infrastructure/database/config.js',
    '!src/infrastructure/security/README.md',
    '!src/infrastructure/security/SECURITY-IMPLEMENTATION-STATUS.md',
    '!src/**/index.ts',
    '!src/infrastructure/security/apply-security-to-controllers.ts',
    '!src/infrastructure/security/update-remaining-controllers.ts',
    '!src/infrastructure/security/sequelize-security.config.ts',
    '!src/infrastructure/services/s3-upload.service.ts',
    '!src/infrastructure/services/cloudwatch-logger.service.ts',
    '!src/infrastructure/services/cloudwatch-metrics.service.ts',
    '!src/infrastructure/services/audit-log.service.ts',
    '!src/infrastructure/observability/**',
    '!src/interfaces/http/controllers/audit-log.controller.ts',
    '!src/interfaces/http/controllers/database.controller.ts',
    '!src/interfaces/http/controllers/upload.controller.ts',
    '!src/infrastructure/strategies/**',
    '!src/infrastructure/providers/**',
    '!src/infrastructure/security/validation.decorators.ts',
    '!src/infrastructure/security/security.module.ts',
    '!src/**/*.config.ts',
  ],
  coverageThreshold: {
    global: {
      statements: 80,
      branches: 70,
      functions: 80,
      lines: 80,
    },
  },
};

export default config;
